### ISSUE TITLE
Switch http-extensions to GitHub Actions

### ISSUE THREAD

**Issue by mnot** [httpwg/admin#1]
@martinthomson should this be relatively straightforward?

/cc @MikeBishop

**Comment by mnot** [comment]
https://mailarchive.ietf.org/arch/msg/ietf-and-github/6CzF7BtvcrPBq2Teu4F3aGo5iIc

**Comment by martinthomson** [comment]
I believe that most of the kinks have been worked out of the process.  Happy to be on standby during a changeover in case my crude instructions fail.

**Comment by mnot** [comment]
I see that you don't have `lib` in your [template .gitignore](https://github.com/martinthomson/i-d-template/blob/main/template/.gitignore), but it is in [http-extension's](https://github.com/httpwg/http-extensions/blob/master/.gitignore). What do you recommend?

**Comment by martinthomson** [comment]
That is added programmatically. If someone chooses to use submodules, including `lib` breaks things, so it needs to be flexible.

**Comment by mnot** [comment]
Seems to be working...
