### ISSUE TITLE
HTTP2 GH org

### ISSUE THREAD

**Issue by mnot** [httpwg/admin#11]
So, HTTP/2 was one of the first big IETF efforts that used GitHub, and we gave it its own GitHub org:
  https://github.com/http2

If we're going to start working on bis, we should figure out the status of this org.

I'm thinking we should move the following repos to the httpwg organisation:

- http2-spec
- compression-test  (this is still useful for testing other ways of compressing things)
- http_samples ?

The rest of the repos can stay there and be archived, with the exception of the Web site, which should be update to point to the HTTP WG home page (migrating some material, possibly). And we'd probably put some text in the org description pointing people to httpwg.

Does all of that make sense? Other thoughts? 

@martinthomson, I see that you forked http2-spec for your bis proposal; my assumption is that that will eventually turn into a PR against httpwg/http2-spec. 

The only thing that's giving me slight pause here is that if we use the same repo for h2bis, the issues will become intermingled. I don't currently see how that would cause problems (because we can filter by dates, etc.).

/cc @tfpauly

**Comment by martinthomson** [comment]
I'm happy to do whatever works best.

If the thrust of your thinking is toward merging http2 into httpwg and using a new repo for h2bis, I agree that's sensible.  Mingling issue history is likely to produce a bad outcome.  I only forked because that was easiest.  If I'm really good, I can excise most of the original commits from my repo, so that the new one starts from the state in which the original left off.

A redirect is probably good enough for the site.

**Comment by mnot** [comment]
I was thinking of migrating http2-spec to httpwg, and then merging your branch into it (assuming that we adopt h2bis).

If intermingling of issues or history is a real problem, we can use a separate repo -- but I don't yet see that as warranted. Can you expand upon your concern about mingling issue history?

**Comment by martinthomson** [comment]
OK, I misread your original post.  I am OK with merging history, but there is a lot of cruft to deal with.  Hopefully that can be worked through.

**Comment by mnot** [comment]
I've moved over `http2-spec` and `compression-test`. Not sure if `http_samples` is useful yet, so will leave for now. I've archived the other repos.

Closing this; I suspect that `httpwg/http2-spec` needs some adjustments, but that can take place over there.
