### ISSUE TITLE
SEARCH method

### ISSUE THREAD

**Issue by mnot** [httpwg/admin#2]
See [draft-snell-search-method](https://tools.ietf.org/html/draft-snell-search-method).

**Comment by mitar** [comment]
Just a quick question, maybe bike shedding. Why call it `SEARCH` and not `QUERY` given that the spec itself says:

> the SEARCH method is used to ask the server to perform a query operation (described by the request payload) over some set of data scoped to the effective request URI.

I think QUERY is much more general than SEARCH, and could nicely map to complex query uses, like GraphQL.

**Comment by mnot** [comment]
Just a note - this repo is for managing the adoption of the draft, not technical discussion about it.

**Comment by mitar** [comment]
Which place is better? The issue in http-extensions was closed, and also linked draft is an expired one.

**Comment by mnot** [comment]
Until it's adopted by the group, we're not formally discussing it.

**Comment by stokito** [comment]
I read the https://github.com/httpwg/http-extensions/blob/master/CONTRIBUTING.md and as far I understood the only way to discuss is email list, right?
Because I have some thoughts against the new SEARCH method (similar to what @mitar said) but not sure how to discuss it: should I find some other letter or start a new thread.

**Comment by mnot** [comment]
Best place is the mailing list, correct.

**Comment by mnot** [comment]
Discussed in the October 2020 interim meeting; candidate for Call for Adoption.

**Comment by mnot** [comment]
Discussed on list:
 https://www.w3.org/mid/F0556EC2-D5AD-47FF-A780-15949F57A911@mnot.net

Seems to be strong interest in this area, but scope needs to be open regarding things like method name, cache ability, etc. Don't detect actual disagreements yet, just areas to be discussed.

Adopting.

**Comment by piotr-dobrogost** [comment]
What's the status?

**Comment by asbjornu** [comment]
@piotr-dobrogost the draft is being discussed in the [`http-extensions` repository](https://github.com/httpwg/http-extensions). You can follow the active issues tagged with the [`query-method` label](https://github.com/httpwg/http-extensions/issues?q=is%3Aissue+is%3Aopen+label%3Aquery-method).
