### ISSUE TITLE
Redirecting 404

### ISSUE THREAD

**Issue by annevk** [httpwg/admin#21]
Has there ever been discussion for a status code that means "this URL does not exist, but let me redirect you to a URL that does and might help you"?

Especially for URLs that are meant to be human-readable this would be really helpful. Or if you want to help the user by eliding punctuation that might have ended up at the end of a URL due to bad auto-linking. (And in practice I've seen this implemented with a 3xx status code and I suppose 301 kinda fits the bill, but it's a little strange?)

(This also applies a bit to 410 and maybe other 4xx status codes.)

(Sorry if this is the wrong place.)

**Comment by mnot** [comment]
Closing as this seems to have concluded. Anne, if you have a concrete proposal or more data, please come back. You might get a broader response if you ask on the mailing list (yes, I know...).

Cheers
