### ISSUE TITLE
style guide: references

### ISSUE THREAD

**Issue by LPardue** [httpwg/admin#29]
https://github.com/httpwg/admin/blob/main/style-guide.md#references is IMO not very clear to a casual observer. I think it might just be better to state that named references are preferred over RFC numbers, and then list concrete examples of common documents that HTTP WG docs are likely to need. For instance, when referencing HTTP semenantics I think the preference is `HTTP` rather than `SEMANTICS`. Structured Fields will also similarly be referenced a lot and a common way to ref it might help things.

**Comment by mnot** [comment]
I was wondering if we should start a mini-registry of preferred names on the page...
