### ISSUE TITLE
Structured Fields ref details

### ISSUE THREAD

**Issue by mnot** [httpwg/admin#36]
Do we want a spec to refer to SF every time it uses a term, like this:

> Each member of the Foo header (a Dictionary, per {{Section 3.2 of STRUCTURED-HEADERS}})
> is an Integer (see {{Section 3.3.1 of Structured Headers}}).

Or just rely on declaration of terminology in Notational Conventions (and capitalisation), so that it would be:

> Each member of the Foo header (a Dictionary) is an Integer.

?

I'm leaning towards the latter...

**Comment by ioggstream** [comment]
My 2¢:

- rely on Notational Convention and Capitalisation
- editorial features can support linking

**Comment by mnot** [comment]
The RPC has pointed out that they need to use [RFC8941] style references in IANA registry entries, which argues pretty strongly for the latter approach.

I'll update the style guide accordingly.
