### ISSUE TITLE
Referencing fields question

### ISSUE THREAD

**Issue by ioggstream** [httpwg/admin#38]
## Question

In https://github.com/httpwg/admin/blame/main/style-guide.md#L33 I was guessing - once a field has been defined which is the benefit to repeat in more than one place the term "field", "header field", ... .
My impression is that backticks eg `Content-Location`, `Content-Type` improve readability a lot wrt just having unquoted strings followed by "header field".

**Comment by mnot** [comment]
No, because backpacks make the text rendering look horrible.
