### ISSUE TITLE
style: consider some styling for the HTML version

### ISSUE THREAD

**Issue by LPardue** [httpwg/admin#42]
I've so far been looking at the [markdown](https://github.com/httpwg/admin/blob/main/editors/style-guide.md) version, which does a nice job of differentiating instruction from example. However,  over on https://httpwg.org/admin/editors/style-guide, things are less clear and it looks more like a wall of text. It would help to make the examples look more like examples.

**Comment by LPardue** [comment]
Oh and there's some brokeness going on, e.g.

![image](https://user-images.githubusercontent.com/6571445/160955072-f9cc9be4-78e2-443e-9ccb-093c7a85ae49.png)

**Comment by mnot** [comment]
OK, this should be better now.
