### ISSUE TITLE
Where should TAG Security & Privacy Questionnaire Answers go?

### ISSUE THREAD

**Issue by arichiv** [httpwg/admin#43]
I ended up putting one [here](https://github.com/httpwg/http-extensions/blob/main/tag/cookie-expires-clamping.md) for a [review](https://github.com/w3ctag/design-reviews/issues/729). Is this a reasonable location?

**Comment by mnot** [comment]
Questions like this go in httpwg/admin.

I think the best thing to do would be to create an issue in the spec's repo, rather than add a file to it. If a separate document is needed for some reason (I don't think it is for TAG reviews), it can go in httpwg/wiki/wiki.
