### ISSUE TITLE
Cannot send an email to the mailing list

### ISSUE THREAD

**Issue by falsandtru** [httpwg/admin#57]
My mailing list subscription application has been in the following status since about Nov 25th. Approved but can neither receive nor send.

ID already processed

Error: The message with id: xxx has already been processed (approved).

**Comment by mnot** [comment]
e-mail `contact@w3.org` and describe your problem.

**Comment by falsandtru** [comment]
I contacted that address. I received the following reply. That address does not seem to be the contact for this kind of problem.

```
*** NOTE ***

Your message was sent from an address which is not on the list
of people who are authorized to post to this mailing list. Your
message has been forwarded to the list maintainer for review.

If you are subscribed to the list or have access to the archives
you may be able to verify that your message has been distributed.
If you have not been able to verify this within a few business days
you can contact the list maintainer by replying to this message.

If you have a W3C account you can avoid delays by making sure
any addresses you use are associated with your user profile:

    https://www.w3.org/users/myprofile/edit/emails/

Thank you

W3C Postmaster
https://www.w3.org/email/
```

**Comment by falsandtru** [comment]
I finally solved this by subscribing to the mailing list. But I think the function to send without subscribing to the mailing list is still broken.

**Comment by mnot** [comment]
You need to subscribe to the list to send e-mail to it.
