### ISSUE TITLE
Existing HTTP/2 Extensions in HTTP/3

### ISSUE THREAD

**Issue by mnot** [httpwg/admin#9]
https://datatracker.ietf.org/doc/html/draft-bishop-httpbis-altsvc-quic

**Comment by mnot** [comment]
@MikeBishop FYI - this is tracking your draft. If/when you think it's time for a CfA please ping here.

**Comment by MikeBishop** [comment]
With HTTP/3 close to being done in the QUIC WG, it's probably a good time for this one, too.  It's pretty straightforward, I think.

**Comment by mnot** [comment]
Discussed in October 2020 interim; this could be a separate document, or it could be bis of ORIGIN and AltSvc (provided the scope can be kept tight).

**Comment by mnot** [comment]
The relevant extensions are:

- [x] AltSvc
- [ ] ORIGIN
- [x] WebSockets extended CONNECT

**Comment by MikeBishop** [comment]
ORIGIN:  draft-bishop-httpbis-origin-h3-00

...unless we think we'd rather do a full bis.

**Comment by mnot** [comment]
CfA for origin issued, so closing.
